development:
  clients:
    default:
      database: bingo
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 5
